#! /bin/bash
alias ROS2='. ~/ros2_humble/install/setup.bash
echo "ROS2 is go!"'
alias talker='ros2 run demo_nodes_cpp talker'
alias listener='ros2 run demo_nodes_cpp listener'
#Husarnet
alias husar='export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
export FASTRTPS_DEFAULT_PROFILES_FILE=/var/tmp/husarnet-fastdds-simple.xml
echo "Husarnet hurdles jumped!"'
alias demotime='ROS2
husar
husarnet status
echo "***demo time!***"'
